# Template for Data Processing System
# This YAML file defines a template for processing data in a specific use case.
# It includes definitions for each data field, their types, labels, and transformations.

template:
  name: "CustomerDataProcessor"
  purpose: "To process and transform customer data for analysis"

data_fields:
  - field_name: "customer_id"
    field_type: "string"
    field_label: "Customer ID"
    transformations:
      - type: "trim"
        description: "Remove leading and trailing spaces"

  - field_name: "purchase_amount"
    field_type: "float"
    field_label: "Purchase Amount"
    transformations:
      - type: "round"
        description: "Round to 2 decimal places"
        parameters:
          decimal_places: 2

  - field_name: "purchase_date"
    field_type: "date"
    field_label: "Purchase Date"
    transformations:
      - type: "format_date"
        description: "Convert to YYYY-MM-DD format"
        parameters:
          input_format: "MM/DD/YYYY"
          output_format: "YYYY-MM-DD"

  - field_name: "email"
    field_type: "string"
    field_label: "Email Address"
    transformations:
      - type: "lowercase"
        description: "Convert to lowercase"

  - field_name: "customer_feedback"
    field_type: "text"
    field_label: "Customer Feedback"
    transformations:
      - type: "sentiment_analysis"
        description: "Perform sentiment analysis on feedback text"

# Add more fields as required for the specific data processing needs