# Template for Processing Fake Airline Manifest Data

template:
  name: "fake_airline_manifest"
  primary_key: "passenger_info"

rename_fields:
  - from: "passenger_info"
    to: "passenger_information"
  - from: "full_name"
    to: "name"
  - from: "date_of_birth"
    to: "dob"
  - from: "country_of_citizenship"
    to: "country"

standardize_fields:
  - field: "name"
    transform: "standardize_name"
  - field: "dob"
    transform: "standardize_date"
  - field: "country"
    transform: "standardize_country"

entities:
  - name
  - passport_id

embeddings:
  - name

datetime_fields:
  - dob

drop_fields:
  - id_type

relationships:
  - parents: ["passport_id"]
    children: ["name", "dob", "country", "id_type"]
    type: "one_to_one"
