# Template for Processing Fake Airline Manifest Data

template:
  name: "fake_airline_manifest"
  purpose: "Analysis of fake airline manifest data"
  primary_key: "passenger_info"

rename_fields:
  - from: "passport_id"
    to: "passenger_info"
  - from: "full_name"
    to: "name"
  - from: "date_of_birth"
    to: "dob"
  - from: "country_of_citizenship"
    to: "country"

standardize_fields:
  - field: "name"
    transform: "standardize_name"
  - field: "dob"
    transform: "standardize_date"
  - field: "country"
    transform: "standardize_country"

relationships:
  - parents: ["passport_id"]
    children: ["name", "dob", "country", "id_type"]
    type: "one_to_one"
