# Template for Processing Fake Airline Manifest Data

template:
  name: "fake_airline_manifest_passengers"
  primary_key: "passenger_info"

rename_fields:
  - from: "passport_information"
    to: "passport_id"
  - from: "full_name"
    to: "name"
  - from: "date_of_birth"
    to: "dob"
  - from: "country_of_citizenship"
    to: "country"

standardize_fields:
  - field: "name"
    transform: "standardize_name"
  - field: "dob"
    transform: "standardize_date"
  - field: "country"
    transform: "standardize_country"
  - field: "passport_id"
    transform: "standardize_passport_id"

entities:
  - name
  - passport_id

embeddings:
  - name

datetime_fields:
  - field: "dob"
    is_created_at: false

drop_fields:
  - id_type

edges:
  - parents: ["passport_id"]
    children: ["name", "dob", "country", "id_type"]
    type: "one_to_one"

edge_properties:
  - time_to_departure
