# Template for Processing Fake Airline Manifest Data

template:
  name: "fake_airline_manifest_flight"
  primary_key: "flight_information"

fields:
  - field: "flight_manifest_id"
    alias: ""
    standardize: "standardize_name"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "city_of_departure"
    alias: "city"
    standardize: "standardize_geography"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "departure_airport_name"
    alias: "airport"
    standardize: "standardize_name"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "city_of_arrival"
    alias: "city"
    standardize: "standardize_geography"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "arrival_airport_name"
    alias: "airport"
    standardize: "standardize_name"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "airline_name"
    alias: "airline"
    standardize: "standardize_name"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "flight_number"
    alias: ""
    standardize: "standardize_name"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "departure_gate"
    alias: "gate"
    standardize: "standardize_name"
    is_entity: false
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "departure_time"
    alias: ""
    standardize: "standardize_date"
    is_entity: false
    is_embedding: false
    is_datetime: true
    drop: false
  - field: "arrival_gate"
    alias: "gate"
    standardize: "standardize_name"
    is_entity: false
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "arrival_time"
    alias: ""
    standardize: "standardize_date"
    is_entity: false
    is_embedding: false
    is_datetime: true
    drop: false
  - field: "time_to_departure"
    alias: ""
    standardize: "standardize_date"
    is_entity: false
    is_embedding: false
    is_datetime: false
    drop: false

calculated_entities:
  - fields: ["city_of_departure", "departure_airport_name", "departure_gate", "departure_time"]
    alias: "departure"

edges:
  - parents: ["flight_manifest_id"]
    children: ["airline_name", "flight_number"]
    properties: ["time_to_departure"]
    direction: "out"
    type: "one_to_one"
  - parents: ["flight_number"]
    children: ["airline_name", "city_of_departure", "departure_airport_name", "departure_gate", "departure_time", "city_of_arrival", "arrival_airport_name", "arrival_gate", "arrival_time"]
    properties: []
    direction: "out"
    type: "one_to_one"
