# Template for Processing Fake Airline Manifest Data

template:
  name: "fake_airline_manifest_passengers"
  primary_key: "passenger_info"
  namespace: "passenger"

fields:
  - field: "full_name"
    alias: "name"
    standardize: "standardize_name"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "gender"
    alias: ""
    is_entity: false
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "date_of_birth"
    alias: "dob"
    standardize: "standardize_date"
    is_entity: false
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "country_of_citizenship"
    alias: "country"
    standardize: "standardize_geography"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "government_id_type"
    alias: "id_type"
    is_entity: false
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "passport_information"
    alias: "passport_id"
    standardize: "standardize_passport_id"
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false
  - field: "flight_manifest_id"
    alias: ""
    is_entity: true
    is_embedding: false
    is_datetime: false
    drop: false

calculated_entities:
  - fields: ["full_name", "date_of_birth", "country_of_citizenship"]
    alias: "identity"

edges:
  - parents: ["flight_manifest_id"]
    children: ["full_name"]
    properties: [""]
    direction: "out"
    type: "one_to_one"
  - parents: ["full_name"]
    children: ["government_id_type", "passport_information"]
    properties: [""]
    direction: "out"
    type: "one_to_one"

